# Generated by Django 3.1.1 on 2020-09-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_auto_20200930_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Textbooks', 'Textbooks'), ('JEE Books', 'JEE Books'), ('Stationery', 'Stationery')], max_length=50, null=True),
        ),
    ]
