# Generated by Django 3.1.1 on 2020-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_auto_20201001_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Textbooks', 'Textbooks'), ('JEE Books', 'JEE Books'), ('Stationery', 'Stationery')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
