# Generated by Django 3.1.1 on 2020-10-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0010_auto_20201001_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Text books', 'Text books'), ('Stationery', 'Stationery'), ('Copies', 'Copies')], max_length=50, null=True),
        ),
    ]
