# Generated by Django 3.1.1 on 2020-10-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0011_auto_20201001_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Text books', 'Text books'), ('Stationery', 'Stationery'), ('Copies', 'Copies')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
